-- ============================================================================
-- Table: export_log
--
-- Description:
-- Stores metadata for export operations generated by the Talent Prism platform.
--
-- This table does not store the exported files themselves. Instead, it records
-- information about each export request, including who initiated the export,
-- what data was exported, how many records were included, and where the
-- generated file can be downloaded.
--
-- Typical export types include applicant data, photo archives, or combined
-- exports generated for recruiters, administrators, or reporting purposes.
--
-- Related Tables
--
-- • intake (Applicant records referenced by the export)
--
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.export_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    exported_by TEXT,

    export_type TEXT,

    record_count INTEGER,

    intake_ids UUID[],

    created_at TIMESTAMPTZ DEFAULT NOW(),

    expires_at TIMESTAMPTZ,

    download_url TEXT,

    CONSTRAINT export_log_export_type_check
        CHECK (
            export_type IN (
                'csv',
                'photos',
                'both'
            )
        )
);

-- ============================================================================
-- Table Comments
-- ============================================================================

COMMENT ON TABLE public.export_log IS
'Stores metadata for export operations generated by the Talent Prism platform.';

COMMENT ON COLUMN public.export_log.id IS
'Unique identifier for the export operation.';

COMMENT ON COLUMN public.export_log.exported_by IS
'User or system account that initiated the export.';

COMMENT ON COLUMN public.export_log.export_type IS
'Type of export generated (csv, photos, or both).';

COMMENT ON COLUMN public.export_log.record_count IS
'Number of applicant records included in the export.';

COMMENT ON COLUMN public.export_log.intake_ids IS
'List of applicant IDs included in the export.';

COMMENT ON COLUMN public.export_log.created_at IS
'Timestamp indicating when the export was generated.';

COMMENT ON COLUMN public.export_log.expires_at IS
'Timestamp indicating when the generated download link expires.';

COMMENT ON COLUMN public.export_log.download_url IS
'Temporary signed URL used to download the exported files.';

-- ============================================================================
-- Column Groups
--
-- Identity
-- • id
--
-- Export Information
-- • exported_by
-- • export_type
-- • record_count
-- • intake_ids
--
-- Download Information
-- • download_url
-- • expires_at
--
-- Audit
-- • created_at
--
-- ============================================================================
-- Recommended Indexes
--
-- Depending on workload, consider creating indexes on:
--
-- • exported_by
-- • export_type
-- • created_at
-- • expires_at
--
-- These indexes have intentionally been omitted because the optimal indexing
-- strategy depends on export frequency and reporting requirements.
--
-- ============================================================================